export const sign_in_page = {
    logo_image: '.makeStyles-logo-3',
    title_text: '.MuiTypography-h5',
    user_name_label: '[id = "username-label"]',
    user_name_input: '#username',
    password_label: '[id = "password-label"]',
    password_input: '#password',
    user_helper_text: '[id = username-helper-text]',
    outside: '.makeStyles-root-1',
    checkbox: '.PrivateSwitchBase-input-14',
    button: '[type="submit"]',
    signup_link: '[href="/signup"]',
    built_by: '.MuiTypography-body2',
    copyright_logo: '[viewBox="0 0 403 135"]',
    copyright_link: '[href="https://cypress.io"]',
    first_name: '#firstName',
    last_name: '#lastName',
    username: '#username',
    user_password: '#password',
    confirm_password: '#confirmPassword',
    sign_up_button: '.MuiButton-label',
    user_test_data: 'UserTestData',
    password_for_test: 'UserPassword',
    user_login_check: '.MuiTypography-subtitle1',
    confirmation_modal: '.MuiDialogContentText-root',
    logout_button: '[data-test="sidenav-signout"]'
}